### PR TITLE
fix: override default `PluginDir` location for when slurmd is used in configless mode

### LINKED ISSUE #17: Slurm configless mode is broken because of bad `PluginDir`
[Slurm configless mode](https://slurm.schedmd.com/configless_slurm.html) is broken due to the baked in `PluginDir` being a bad path. At configure time - _when you run `./configure` before compiling Slurm_ - the `PluginDir` path is baked directly into Slurm to be `//lib/slurm`. See the [slurm.conf manpage](https://slurm.schedmd.com/slurm.conf.html#OPT_PluginDir) for more info.

This path doesn't exist when Slurm has been installed which causes Slurm to fail to start. While this can be fixed by setting the `PluginDir` option in the _slurm.conf_ configuration file, this doesn't work if you are using slurmd in configless mode. This is because Slurm attempts to load plugins __before__ fetching the _slurm.conf_ file from the Slurm controller (slurmctld). Slurm doesn't support overrideable configuration files (e.g. set a lower priority _slurm.conf_ file that Slurm reads before fetching the _slurm.conf_ file from the Slurm controller), so we're unable to preconfigure the correct plugin path at runtime.

What we need to do is modify Makefile.am to point to the correct path __before__ compiling Slurm so that Slurm will find the correct plugin directory __without__ additional modification from a _slurm.conf_ file. Ideally this will just be patch file that we apply to Slurm's code base before we build Slurm itself inside the snap.

Screenshot for additional context:

image

### PR DESCRIPTION
**Pull request by NucciTheBoss**
## Description

This pull request fixes configless mode for slurmd by patching Slurm's `src/common/Makefile.am` file to set the default `PluginDir` and `sysconfig` (_slurm.conf_) locations to snap-specific locations under `$SNAP_COMMON`.

Fixes #17

## Changes

- Add patch for `src/common/Makefile.am` and patch part in _snapcraft.yaml_.
- - Add `--authinfo` to configure munge authentication when running in configless mode.
- Remove `-f` flag from slurmd command when running in configless mode.

## Misc. 

Updates the Slurm version to bugfix version 23.11.7.

### CODE REVIEW

**Comment by jedel1043** [comment]
image

Apparently it works, but still needs the SlurmctldHost and ClusterName options. Is that te correct behaviour?

**Comment by NucciTheBoss** [comment]
Per further investigation, the issue is that we set `SLURM_CONF` to `$SNAP_COMMON/etc/slurm/slurm.conf` in _snapcraft.yaml_. This is fine and dandy until when we're running Slurm in configless mode where the config file is actually located under `$SNAP_COMMON/var/spool/slurmd/conf-cache/slurm.conf`. This breaks all the Slurm CLI commands as they read the `SLURM_CONF` environment variable from their execution environment which points to `$SNAP_COMMON/etc/slurm/slurm.conf`.

Need to fix this before this pull request can land :wrench:

**Review by jedel1043 — APPROVED** [review]
Looks good to me, we can fix the spool problem later.

**Comment by NucciTheBoss** [comment]
Yep, it seems like setting `runstatedir` and `localstatedir` when compiling slurm doesn't have any effect so we'll need to override the PID and spool dir locations directly in the _slurm.conf_ file. Won't be too bad as we can just do this in the install hook when we fix #19.

Might need some fancy logic for locating _slurm.conf_ file when in configless mode, but we'll cross that bridge :bridge_at_night:

**Pull request merged**
